import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Uday",
      email: "admin@flipzon.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "someUser",
      email: "someUser@flipzon.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "X brand Slim Shirt",
      category: "shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "X brand",
      rating: 4.0,
      numReviews: 10,
      description: "Good quality shirt",
      color: "green",
    },
    {
      name: "Y brand Fit Shirt",
      category: "shirts",
      image: "/images/p2.jpg",
      price: 125,
      countInStock: 15,
      brand: "Y brand",
      rating: 4.0,
      numReviews: 8,
      description: "Good quality shirt",
      color: "red",
    },
    {
      name: "Lacoste Shirt",
      category: "shirts",
      image: "/images/p3.jpg",
      price: 120,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.5,
      numReviews: 17,
      description: "Good quality shirt",
      color: "orange",
    },
    {
      name: "X brand Slim pant",
      category: "pants",
      image: "/images/p4.jpg",
      price: 150,
      countInStock: 12,
      brand: "X brand",
      rating: 4.0,
      numReviews: 10,
      description: "Good quality pant",
      color: "red",
    },
    {
      name: "adidas Slim pant",
      category: "pants",
      image: "/images/p5.jpg",
      price: 182,
      countInStock: 3,
      brand: "adidas",
      rating: 5.0,
      numReviews: 5,
      description: "Good quality pant",
      color: "pink",
    },
    {
      name: "Y Brand Slim pant",
      category: "pants",
      image: "/images/p6.jpg",
      price: 100,
      countInStock: 5,
      brand: "Y brand",
      rating: 2.0,
      numReviews: 1,
      description: "Good quality shirt",
      color: "yellow",
    },
  ],
};

export default data;
