const data = {
  products: [
    {
      _id: "1",
      name: "X brand Slim Shirt",
      category: "shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "X brand",
      rating: 4.0,
      numReviews: 10,
      description: "Good quality shirt",
    },
    {
      _id: "2",
      name: "Y brand Fit Shirt",
      category: "shirts",
      image: "/images/p2.jpg",
      price: 125,
      brand: "Y brand",
      rating: 4.0,
      numReviews: 8,
      description: "Good quality shirt",
    },
    {
      _id: "3",
      name: "Lacoste Shirt",
      category: "shirts",
      image: "/images/p3.jpg",
      price: 120,
      brand: "Lacoste",
      rating: 4.5,
      numReviews: 17,
      description: "Good quality shirt",
    },
    {
      _id: "4",
      name: "X brand Slim pant",
      category: "pants",
      image: "/images/p4.jpg",
      price: 150,
      brand: "X brand",
      rating: 4.0,
      numReviews: 10,
      description: "Good quality pant",
    },
    {
      _id: "5",
      name: "adidas Slim pant",
      category: "pants",
      image: "/images/p5.jpg",
      price: 182,
      brand: "adidas",
      rating: 5.0,
      numReviews: 5,
      description: "Good quality pant",
    },
    {
      _id: "6",
      name: "Y Brand Slim pant",
      category: "pants",
      image: "/images/p6.jpg",
      price: 100,
      brand: "Y brand",
      rating: 2.0,
      numReviews: 1,
      description: "Good quality shirt",
    },
  ],
};

export default data;
